# Numpy
NumPy in Python is a powerful library used for numerical computing. It’s especially important for data analysis, machine learning, scientific computing, and competitive programming.


## NumPy (Numerical Python) provides:

1)Fast n-dimensional arrays

2)Mathematical, statistical, and linear algebra functions

3)High performance compared to Python lists


In [1]:
!pip install numpy

## Create an Array

In [ ]:
import numpy as np
 
 ## inside it we can give list ,tuple
arr1=np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape)  ## 1 D



[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [ ]:
arr2=np.array([1,2,3,8,9])

##reshape it to 2D
arr2.reshape(1,5) ##2D 1row ans 5 columns


array([[1, 2, 3, 8, 9]])

In [ ]:
arr2=np.array([[1,2,3,4,5],[12,89,8,9,0]])
##arr2.shape
print(arr2.shape)  ## 2 row and 5 col

(2, 5)


## Arrays with inbuilts function

In [21]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4))  

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
## identity matrox
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Attributes of numpy
arr=np.array([[1,2,3],[2,3,4]])
print("Dimension:",arr.ndim)
print("Size:",arr.size)
print("Data Type:",arr.dtype)
print("Item size(in byte):",arr.itemsize)

Dimension: 2
Size: 6
Data Type: int64
Item size(in byte): 8


## Vectorized Operation


In [ ]:
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])

## Element wise addition
print("Addition:",arr1+arr2)

print("Substraction:",arr1-arr2)
print("Multiplication:",arr1*arr2)


Addition: [11 22 33 44]
Substraction: [ -9 -18 -27 -36]
Multiplication: [ 10  40  90 160]


## Universal Funnction
 To each element

In [35]:
## square root
arr=np.array([1,2,3,4])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))


[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]


## Array Slicing and indexing

In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Arrays:\n",arr)


Arrays:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
print(arr[0][1])

2


In [52]:
arr[1:,2:] ## one to n  row and  2 to n col
# print(arr[0:,1:])
# print(arr[0:2,1:])
# print(arr[1:2,1:])

print(arr[1:3,1:3])


[[ 6  7]
 [10 11]]


In [54]:
## Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [55]:
arr[1:]=-100
print(arr)

[[ 100    2    3    4]
 [-100 -100 -100 -100]
 [-100 -100 -100 -100]]


## Satistical Concept -- Normalization
